name: sahaya-frontend Build
on:
  push:
    branches: 
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run : npm install webpack
      - run : npm install webpack-cli
      - run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundled file
          path: dist/
